apiVersion: apps/v1
kind: Deploy
metadata:
  name: crm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-app
  strategy:
    type: RollingUpdate
  template:
    metadata: 
      labels:
        app: crm-app
    spec:
      containers:
        - name: crm-app
          image: shubhamkalsait1/student-api:latest
          ports:
            - containerPort: 8080

          
