apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: crm-app
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: crm-app